pipeline:
  test:
    image: python:2-slim
    commands:
      - sleep 999999999

#  helming:
#    image: kubeciio/helm
#    pull: true
#    secrets:
#    - source: kubeconfig_do
#      target: kubeconfig
#    helm: list

#  kubectl:
#    image: kubeciio/kubectl
#    pull: true
#    secrets:
#    - source: kubeconfig_do
#      target: kubeconfig
#    kubectl: get pods
#  files:
#  - /path/to/folder/foo.yaml

#  build-docker:
##    image: plugins/docker
#    image: kubeciio/img
##    privileged: true
##    pull: true
#    repo: toschneck/wait-for-it
#    dockerfile: Dockerfile
#    secrets: [ docker_username, docker_password ]