pipeline:
  test:
    image: python:2-slim
    commands:
      - env

#  helming:
#    image: kubeciio/helm
#    pull: true
#    secrets:
#    - source: kubeconfig_do
#      target: kubeconfig
#    helm: list

  kubectl:
    image: toschneck/kubectl:2.2
    pull: true
    secrets:
    - source: kubeconfig_do
      target: kubeconfig
    debug: true
    kubectl: apply
    files:
    - k8c/test.job.yml

#  build-docker:
##    image: plugins/docker
#    image: kubeciio/img
##    privileged: true
##    pull: true
#    repo: toschneck/wait-for-it
#    dockerfile: Dockerfile
#    secrets: [ docker_username, docker_password ]