pipeline:
  test:
    image: python:2-slim
    commands:
      - python test/wait-for-it.py

  build-docker:
    #    image: plugins/docker
    image: kubeciio/img
      privileged: true
      pull: true
      repo: toschneck/wait-for-it
      tag: testa
      dockerfile: Dockerfile
      secrets: [ docker_username, docker_password ]
      when:
        instance: drone-orig.eu.ngrok.io

  kubectl-apply-job:
    image: kubeciio/kubectl:0.2.2
    pull: true
    secrets:
    - source: kubeconfig_do
      target: kubeconfig
#    debug: true
    kubectl: apply
    files:
    - k8c/test.job.yml

  kubectl-check-job:
    image: kubeciio/kubectl:0.2.2
    pull: true
    secrets:
    - source: kubeconfig_do
      target: kubeconfig
    kubectl: wait --for=condition=Complete
    files:
    - k8c/test.job.yml

  kubectl-get-job-logs:
    image: kubeciio/kubectl:0.2.2
    pull: true
    secrets:
    - source: kubeconfig_do
      target: kubeconfig
    kubectl: logs --selector job-name=wait-for-it

  kubectl-delete-job:
    image: kubeciio/kubectl:0.2.2
    pull: true
    secrets:
    - source: kubeconfig_do
      target: kubeconfig
    kubectl: delete
    files:
    - k8c/test.job.yml
    when:
      status:  [ failure, success ]


#  helming:
#    image: kubeciio/helm
#    pull: true
#    secrets:
#    - source: kubeconfig_do
#      target: kubeconfig
#    helm: list

#  build-docker:
##    image: plugins/docker
#    image: kubeciio/img
##    privileged: true
##    pull: true
#    repo: toschneck/wait-for-it
#    dockerfile: Dockerfile
#    secrets: [ docker_username, docker_password ]
  #when http://drone-orig.eu.ngrok.io