pipeline:
  test:
    image: python:2-slim
    commands:
      - python test/wait-for-it.py

  build-docker:
    image: plugins/docker
    repo: toschneck/wait-for-it
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
